---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n1577697/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp catalog.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
