---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n1577697/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp catalog.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .composer.json $DEPLOYPATH
    - /bin/cp .composer.lock $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R PHPMailer-master $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
